### ISSUE TITLE
AU and US Location

### ISSUE THREAD

**Issue by ralph-kudo** [webflorist/storyblok-backup#2]
Hey, Need help in allowing backup for AU/US spaces. I am getting the ff error. But works on EU. 

```
{
  message: 'Not Found',
  status: 404,
  response: 'This record could not be found'
}
```

Great tool btw. Thanks!

**Comment by codeflorist** [comment]
hey @ralph-burstsms,

thanks for reporting this!

i've just released v0.0.4, which adds the parameter `--region`.

check readme or help-command for possible values. let me know if you have any problems!
