### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined

### ISSUE THREAD

**Issue by ralph-kudo** [webflorist/storyblok-backup#5]
![image](https://github.com/user-attachments/assets/41c04b78-54ee-4cab-bd7e-3bdc2c00c50e)

See here also: https://github.com/ecies/js/issues/802

**Comment by dogfrogfog** [comment]
having same issue

**Comment by codeflorist** [comment]
It seems the issue has already been fixed upstream with the release of eciesjs v0.4.10. I'm not getting errors anymore.
