### ISSUE TITLE
feature request: specify data to backup, instead of backing up all the space

### ISSUE THREAD

**Issue by dogfrogfog** [webflorist/storyblok-backup#6]

**Comment by codeflorist** [comment]
@dogfrogfog thanks for your feature request! do you mean limiting backups by type (stories, components, assets, etc.)?

**Comment by dogfrogfog** [comment]
Yes. I would like to provide a list of "types" I want to backup




Also I'm not necessarily want backups to be in /backup folder. It's hardcoded in the package right now (another thing I faced while working with the package)

**Comment by codeflorist** [comment]
OK, i can add that.

The reason, that a backup subfolder is used, is because of the create-zip functionality. The zip itself is also written into `.output`, and if all backup files would be placed there, the zip process would also archive the zip file itself in an endless loop. So i will not change that.

**Comment by codeflorist** [comment]
I've just release v0.3.0, which includes this feature.

**Comment by dogfrogfog** [comment]
> The reason, that a backup subfolder is used, is because of the create-zip functionality. The zip itself is also written into `.output`, and if all backup files would be placed there, the zip process would also archive the zip file itself in an endless loop. So i will not change that.

Yes, but zip functionality is turned by default and there are 3 folders for no reason.

Overriding .output (change it to already created folder) would solve my problem as well

![Screenshot 2024-10-28 at 08 11 38](https://github.com/user-attachments/assets/8e05cebf-a9d3-460b-be1a-19994ed7bdc2)

**Comment by dogfrogfog** [comment]
thanks for adding --types, love it

**Comment by codeflorist** [comment]
> > The reason, that a backup subfolder is used, is because of the create-zip functionality. The zip itself is also written into `.output`, and if all backup files would be placed there, the zip process would also archive the zip file itself in an endless loop. So i will not change that.
> 
> Yes, but zip functionality is turned by default and there are 3 folders for no reason.
> 
> Overriding .output (change it to already created folder) would solve my problem as well
> 
> ![Screenshot 2024-10-28 at 08 11 38](https://private-user-images.githubusercontent.com/47758224/380611927-8e05cebf-a9d3-460b-be1a-19994ed7bdc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTAzMzksIm5iZiI6MTczMDExMDAzOSwicGF0aCI6Ii80Nzc1ODIyNC8zODA2MTE5MjctOGUwNWNlYmYtYTlkMy00NjBiLWJlMWEtMTk5OTRlZDdiZGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDEwMDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZGVlZDQxYWYxODBmOGIxOTM3MzgyYmFmYTM4ZDc4MzI4Yjk5NmRhYTkxYWNhOTY3YzRkYTI2MzczNzFlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jDjnFaJAsInSL9OLlXMPwsgQrvwX9Xn5Jui2QAQGUKA)

I would find having different folder structure depending on zip option more confusing than helpful. Think of `.output` as the working directory. I don't think the additional folder is that of a hassle. So i don't have plans to change that at the moment, sorry.
