### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by SebastianKempf** [webflorist/storyblok-backup#7]
Hey webflorist, 
Thanks for the great script! I have been using it to automatically backup a storyblok space to a github repository.
It really worked great up until September 3rd. Since then I am getting the warning 

```
Run actions/upload-artifact@v4
Warning: No files were found with the provided path: .output. No artifacts will be uploaded.
```

when I run the following action script:

```
name: Daily Storyblok Backup

on: 
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Perform Backup
        env:
          STORYBLOK_OAUTH_TOKEN: ${{ secrets.STORYBLOK_OAUTH_TOKEN }}
          STORYBLOK_SPACE_ID: ${{ secrets.STORYBLOK_SPACE_ID }}
        run: npx storyblok-backup --token $STORYBLOK_OAUTH_TOKEN --space $STORYBLOK_SPACE_ID --with-asset-files

      - name: Delete Old Artifacts
        uses: actions/github-script@v7
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
            })
            res.data.artifacts
                .filter(({ name }) => name === 'daily-backup')
                .forEach(({ id }) => {
                  github.rest.actions.deleteArtifact({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      artifact_id: id,
                  })
                })
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-backup
          path: .output
```

and their are no backup files available within the repository.

also when I simply run 

`npx storyblok-backup --token {{TOKEN}} --space {{SPACE_ID}} --with-asset-files`

using Node.js v20.6.1 on my local machine I get the following error message

```
Creating backup for space {{SPACE_ID}}:
Output dir: ./.output
Fetching space
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2331:5)
    at writeJson (file:///Library/WebServer/Documents/node_modules/storyblok-backup/bin/storyblok-backup.mjs:189:5)
    at file:///Library/WebServer/Documents/node_modules/storyblok-backup/bin/storyblok-backup.mjs:210:3
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Library/WebServer/Documents/node_modules/storyblok-backup/bin/storyblok-backup.mjs:208:1 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

When I log the variable space.data in line 189 of storyblok-backup.mjs it returns an object with the key „spaces“ representing an array of spaces:

```
{
  spaces: [
    {
      name: {{NAME_OF_SPACE}},
      id: {{SPACE_ID}},
      euid:  {{EU_ID}},
      region: 'eu-central-1',
      owner_id: {{OWNER_ID}},
      updated_at: '2024-10-22T11:15:36.878Z',
      fe_version: 'v2',
      plan: 'Entry',
      plan_level: 200,
      pending_traffic_boosts: null,
      pending_limit_boosts: null,
      trial: false,
      requires_2fa: false,
      created_at: '2024-02-28T12:53:20.571Z',
      org_id: null,
      partner_id: null,
      subscription_status: '',
      stripe_trial_status: 'subscribed',
      stripe_trial_end: '2024-05-29T07:56:00.000Z',
      space_type: null,
      canceled_at: null,
      org_requires_2fa: false,
      unpaid_at: null,
      blocked_at: null,
      development_mode: false,
      feature_limit_exceeded_flags: [Object]
    }
  ]
}
```
According to the module code an object with the key „space“ representing an object of one space is expected.
Might the API has changed? Unfortunatly I can't make sense of this exacly.
Do you know what might be the problem?

**Comment by codeflorist** [comment]
The first problem is due to this change of GitHub's `upload-artifact` action:
https://github.com/actions/upload-artifact/issues/602

The output-folder `.output` is treated as a hidden folder, and those are automatically excluded since this change. You have to add `include-hidden-files: true` in the action's options. I've updaded the example in the README accordingly.

The second problem is a weird one.

According to the docs of Storyblok's management API [here](https://www.storyblok.com/docs/api/management/core-resources/spaces/retrieve-a-single-space) retrieving of a singular space via the `/spaces/:space_id` endpoint should return a singular object under the `space` key.

It seems in your case, the space-id is omitted, calling the endpoint `/spaces/` instead, which returns an array under a `spaces` key (see docs [here](https://www.storyblok.com/docs/api/management/core-resources/spaces/retrieve-multiple-spaces)).

Could you try logging the variable `spaceId` just before line 208? My assumption is, that it is an empty string.

Problem is, i could not replicate this case. Even if i state an empty string as the space param (`--space ""`), a 404 error is thrown instead of your error, since the variable will be `undefined`.

**Comment by SebastianKempf** [comment]
Thanks for the fast reply! 

The `include-hidden-files: true` issue must have passed me by … now it works fine again! 

regarding the second problem:

I logged the spaceId as follows:

```
// Fetch space info
console.log(`Fetching space`)
console.log(spaceId)

await StoryblokMAPI.get(`spaces/${spaceId}/`)
	.then((space) => {
		writeJson(null, `space-${spaceId}`, space.data.space)
	})
	.catch((error) => {
		throw error
	})
```

and got the following result in my console:

```
npx storyblok-backup --token {{ TOKEN }}- --space #000000 --with-asset-files

Creating backup for space #000000:
Output dir: ./.output
Fetching space
#000000
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2331:5)
    at writeJson (file:///Library/WebServer/Documents/node_modules/storyblok-backup/bin/storyblok-backup.mjs:189:5)
    at file:///Library/WebServer/Documents/node_modules/storyblok-backup/bin/storyblok-backup.mjs:212:3
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Library/WebServer/Documents/node_modules/storyblok-backup/bin/storyblok-backup.mjs:210:1 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
where `#000000` represents the space id of my storyblok space as in a six digit number with a hash before it.

If this is a strange issue that you cannot reproduce don't worry too much about it. I originally thought the two issues might be connected and I only use the github repository version for backups not the local one.

**Comment by codeflorist** [comment]
Ah, then i guess it must be the hash. Try without the #.

**Comment by SebastianKempf** [comment]
Okay, now I feel a bit stupid : )

Works fine without the #! Thanks again.

**Comment by codeflorist** [comment]
👍
