### ISSUE TITLE
Fails with JSON assets

### ISSUE THREAD

**Issue by mgilbertakm** [webflorist/storyblok-backup#8]
Great to see a one-stop-shop tool for backing up Storyblok

Tried it out with our site and struck a problem with an asset which is a JSON file... the metadata is stored as <ID>.json then the file itself is stored as <ID>.<ext> which is, of course .json so it errors with

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: EEXIST: file already exists, open 'C:\Projects\backup\.output\backup\assets\95786.json'] {
  errno: -4075,
  code: 'EEXIST',
  syscall: 'open',
  path: 'C:\\Projects\\backup\\.output\\backup\\assets\\95786.json'
}

**Comment by codeflorist** [comment]
@mgilbertakm

Thanks for the bug report!

Ah yes, i haven't thought of that. Of course that leads to a problem.

I've just released v.0.5.0 with a fix for that. Now asset-files will be saved in a separate asset-files folder instead of the assets folder.
